In [2]:
#importing libraries for numpy, plot and pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#importing breast cancer dataset
from sklearn.datasets import load_breast_cancer
breast = load_breast_cancer()

In [4]:
#loading the input variables into a matrix
breast_data = breast.data
breast_data.shape

(569, 30)

In [5]:
#converting the input variables matrix into a 2D panda array
breast_input = pd.DataFrame(breast_data)
breast_input.head()

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9   ...     20     21      22      23      24      25      26      27  \
0  0.07871  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.05667  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.05999  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.09744  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.05883  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       28       29  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 30 columns]

In [6]:
#loading the outputs into a matrix
breast_labels = breast.target
breast_labels.shape

(569,)

In [7]:
breast_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
#reshaping the output row matrix into a column
labels = np.reshape(breast_labels,(569,1))

In [9]:
#concatenating the input variables and outputs into the same 2D array to create the final dataset
final_breast_data = np.concatenate([breast_data,labels],axis=1)

In [10]:
final_breast_data.shape

(569, 31)

In [11]:
#loading the feature names for the input variables
breast_dataset = pd.DataFrame(final_breast_data)
features = breast.feature_names
features

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [12]:
features_labels = np.append(features,'label')

In [13]:
breast_dataset.columns = features_labels

In [14]:
breast_dataset

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  label  
0                  0.2654          0.4601                  0.11890    0.0  
1                  0.1860          0.2750                  0.08902    0.0  
2                  0.2430          0.3613                  0.08758    0.0  
3                  0.2575          0.6638                  0.17300    0.0  
4                  0.1625          0.2364                  0.07678   

In [15]:
breast_dataset['label'].replace(0, 'Benign',inplace=True)
breast_dataset['label'].replace(1, 'Malignant',inplace=True)

In [16]:
breast_dataset

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension      label  
0                  0.2654          0.4601                  0.11890     Benign  
1                  0.1860          0.2750                  0.08902     Benign  
2                  0.2430          0.3613                  0.08758     Benign  
3                  0.2575          0.6638                  0.17300     Benign  
4                  0.1625          0.2364        

In [17]:
#importing standard scalar and standarding the input values
from sklearn.preprocessing import StandardScaler
# Separating out the features
x = breast_dataset.loc[:, features].values
# Standardizing the features
x = StandardScaler().fit_transform(x)

In [18]:
#importing Principal Component Analysis
from sklearn.decomposition import PCA
pca = PCA(n_components=9)
principalComponents = pca.fit_transform(x)
principalComponents = pd.DataFrame(principalComponents)
principalComponents

0          1         2         3         4         5         6  \
0     9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159370   
1     2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013357   
2     5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668166   
3     7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053422  1.429911   
4     3.935302  -1.948072  1.389767  2.940639  0.546747 -1.226495 -0.936212   
..         ...        ...       ...       ...       ...       ...       ...   
564   6.439315  -3.576817  2.459487  1.177314 -0.074824 -2.375193 -0.596129   
565   3.793382  -3.584048  2.088476 -2.506028 -0.510723 -0.246710 -0.716326   
566   1.256179  -1.902297  0.562731 -2.089227  1.809991 -0.534447 -0.192759   
567  10.374794   1.672010 -1.877029 -2.356031 -0.033742  0.567936  0.223082   
568  -5.475243  -0.670637  1.490443 -2.299157 -0.184703  1.617837  1.698951   

            7         8  
0   -0.398409 -0.157129  
1    0.240990 -0.711904  
2    0.097371  0.024065  
3    1.059562 -1.405433  
4    0.636376 -0.263803  
..        ...       ...  
564 -0.035471  0.987941  
565 -1.113358 -0.105200  
566  0.341889  0.393922  
567 -0.280242 -0.542039  
568  1.046349  0.374088  

[569 rows x 9 columns]

In [19]:
#Setting the principal components as the input variables
X = principalComponents.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8]].values
Y = breast_dataset.iloc[:, 30].values

In [20]:
X

array([[ 9.19283683,  1.94858307, -1.12316616, ...,  2.15937013,
        -0.3984093 , -0.15712924],
       [ 2.3878018 , -3.76817174, -0.52929269, ...,  0.013357  ,
         0.24099032, -0.71190374],
       [ 5.73389628, -1.0751738 , -0.55174759, ..., -0.66816611,
         0.09737101,  0.02406454],
       ...,
       [ 1.25617928, -1.90229671,  0.56273052, ..., -0.19275858,
         0.3418894 ,  0.39392245],
       [10.37479406,  1.67201011, -1.87702933, ...,  0.22308247,
        -0.28024179, -0.5420386 ],
       [-5.4752433 , -0.67063679,  1.49044308, ...,  1.69895143,
         1.04634876,  0.37408835]])

In [21]:
Y

array(['Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8, test_size=0.2, random_state=10)

In [23]:
from sklearn.svm import SVC

In [24]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit=True, cv=5)
grid.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']})

In [25]:
grid.best_params_

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

In [26]:
Y_pred = grid.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

In [28]:
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("\n")
print("Classification Report:\n",classification_report(Y_test, Y_pred))

Confusion Matrix:
 [[38  1]
 [ 3 72]]


Classification Report:
               precision    recall  f1-score   support

      Benign       0.93      0.97      0.95        39
   Malignant       0.99      0.96      0.97        75

    accuracy                           0.96       114
   macro avg       0.96      0.97      0.96       114
weighted avg       0.97      0.96      0.97       114



In [29]:
from sklearn import metrics
pos_label=['Benign', 'Malignant']
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("Precision:",metrics.precision_score(Y_test, Y_pred, pos_label= "Malignant"))
print("Recall:",metrics.recall_score(Y_test, Y_pred, pos_label= "Malignant"))

Accuracy: 0.9649122807017544
Precision: 0.9863013698630136
Recall: 0.96


In [30]:
#importing Principal Component Analysis
from sklearn.decomposition import PCA
pca = PCA(n_components=7)
principalComponents = pca.fit_transform(x)
principalComponents = pd.DataFrame(principalComponents)
principalComponents

0          1         2         3         4         5         6
0     9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159367
1     2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013363
2     5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541451 -0.668162
3     7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053423  1.429907
4     3.935302  -1.948072  1.389767  2.940639  0.546748 -1.226493 -0.936222
..         ...        ...       ...       ...       ...       ...       ...
564   6.439315  -3.576817  2.459487  1.177314 -0.074824 -2.375193 -0.596129
565   3.793382  -3.584048  2.088476 -2.506028 -0.510723 -0.246710 -0.716326
566   1.256179  -1.902297  0.562731 -2.089227  1.809991 -0.534447 -0.192757
567  10.374794   1.672010 -1.877029 -2.356031 -0.033742  0.567937  0.223075
568  -5.475243  -0.670637  1.490443 -2.299157 -0.184703  1.617837  1.698951

[569 rows x 7 columns]

In [31]:
#Setting the principal components as the input variables
X = principalComponents.iloc[:, [0, 1, 2, 3, 4, 5, 6]].values
Y = breast_dataset.iloc[:, 30].values

In [32]:
X

array([[ 9.19283683,  1.94858307, -1.12316619, ..., -1.19511016,
         1.41142403,  2.15936734],
       [ 2.3878018 , -3.76817174, -0.52929269, ...,  0.62177491,
         0.02865594,  0.01336345],
       [ 5.73389628, -1.0751738 , -0.55174761, ..., -0.17708601,
         0.54145149, -0.66816151],
       ...,
       [ 1.25617928, -1.90229671,  0.56273053, ...,  1.8099913 ,
        -0.53444725, -0.19275712],
       [10.37479406,  1.6720101 , -1.87702933, ..., -0.03374183,
         0.56793698,  0.22307544],
       [-5.4752433 , -0.67063679,  1.49044307, ..., -0.1847033 ,
         1.61783717,  1.69895051]])

In [33]:
Y

array(['Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant

In [34]:
#importing train_test_split
#splitting the dataset into 80% and 20% split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8, test_size=0.2, random_state=10)

In [35]:
from sklearn.svm import SVC

In [36]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit=True, cv=5)
grid.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']})

In [37]:
grid.best_params_

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}

In [38]:
Y_pred = grid.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix, classification_report

In [40]:
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("\n")
print("Classification Report:\n",classification_report(Y_test, Y_pred))

Confusion Matrix:
 [[37  2]
 [ 2 73]]


Classification Report:
               precision    recall  f1-score   support

      Benign       0.95      0.95      0.95        39
   Malignant       0.97      0.97      0.97        75

    accuracy                           0.96       114
   macro avg       0.96      0.96      0.96       114
weighted avg       0.96      0.96      0.96       114



In [41]:
from sklearn import metrics
pos_label=['Benign', 'Malignant']
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("Precision:",metrics.precision_score(Y_test, Y_pred, pos_label= "Malignant"))
print("Recall:",metrics.recall_score(Y_test, Y_pred, pos_label= "Malignant"))

Accuracy: 0.9649122807017544
Precision: 0.9733333333333334
Recall: 0.9733333333333334


In [42]:
#importing Principal Component Analysis

from sklearn.decomposition import PCA
pca = PCA(n_components=15)
principalComponents = pca.fit_transform(x)
principalComponents = pd.DataFrame(principalComponents)
principalComponents

0          1         2         3         4         5         6   \
0     9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159370   
1     2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013358   
2     5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668166   
3     7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053422  1.429911   
4     3.935302  -1.948072  1.389767  2.940639  0.546747 -1.226495 -0.936213   
..         ...        ...       ...       ...       ...       ...       ...   
564   6.439315  -3.576817  2.459487  1.177314 -0.074824 -2.375193 -0.596130   
565   3.793382  -3.584048  2.088476 -2.506028 -0.510723 -0.246710 -0.716326   
566   1.256179  -1.902297  0.562731 -2.089227  1.809991 -0.534447 -0.192758   
567  10.374794   1.672010 -1.877029 -2.356031 -0.033742  0.567936  0.223082   
568  -5.475243  -0.670637  1.490443 -2.299157 -0.184703  1.617837  1.698952   

           7         8         9         10        11        12        13  \
0   -0.398407 -0.157118 -0.877402  0.262956 -0.859015  0.103387 -0.690805   
1    0.240988 -0.711905  1.106995  0.813120  0.157923 -0.943529 -0.653475   
2    0.097374  0.024066  0.454275 -0.605604  0.124387 -0.410627  0.016680   
3    1.059565 -1.405440 -1.116975 -1.151513  1.011316 -0.933271 -0.487416   
4    0.636376 -0.263805  0.377704  0.651360 -0.110515  0.387948 -0.539180   
..        ...       ...       ...       ...       ...       ...       ...   
564 -0.035471  0.987929  0.256989 -0.062651  0.123342 -0.051723 -0.404289   
565 -1.113360 -0.105207 -0.108633  0.244804  0.222753 -0.192637  0.015555   
566  0.341887  0.393917  0.520877 -0.840512  0.096473  0.157418  0.285691   
567 -0.280239 -0.542035 -0.089296 -0.178628 -0.697461  1.225195  0.218698   
568  1.046353  0.374101 -0.047726 -0.144095 -0.179496  0.678898 -1.170724   

           14  
0   -0.601779  
1    0.008975  
2    0.483419  
3   -0.168835  
4    0.310317  
..        ...  
564  0.652755  
565 -0.069978  
566  0.090998  
567  0.229602  
568  0.217323  

[569 rows x 15 columns]

In [55]:
#Setting the principal components as the input variables
X = principalComponents.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]].values
Y = breast_dataset.iloc[:, 30].values

In [56]:
X

array([[ 9.19283683e+00,  1.94858307e+00, -1.12316616e+00, ...,
         1.03387428e-01, -6.90804793e-01, -6.01778688e-01],
       [ 2.38780180e+00, -3.76817174e+00, -5.29292687e-01, ...,
        -9.43529316e-01, -6.53474777e-01,  8.97466247e-03],
       [ 5.73389628e+00, -1.07517380e+00, -5.51747593e-01, ...,
        -4.10626593e-01,  1.66799132e-02,  4.83418789e-01],
       ...,
       [ 1.25617928e+00, -1.90229671e+00,  5.62730526e-01, ...,
         1.57417960e-01,  2.85690804e-01,  9.09975882e-02],
       [ 1.03747941e+01,  1.67201011e+00, -1.87702933e+00, ...,
         1.22519476e+00,  2.18697661e-01,  2.29601668e-01],
       [-5.47524330e+00, -6.70636791e-01,  1.49044308e+00, ...,
         6.78897866e-01, -1.17072439e+00,  2.17322755e-01]])

In [57]:
Y

array(['Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Malignant', 'Malignant

In [58]:
#importing train_test_split
#splitting the dataset into 80% and 20% split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8, test_size=0.2, random_state=10)

In [59]:
from sklearn.svm import SVC

In [60]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit=True, cv=5)
grid.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']})

In [61]:
grid.best_params_

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

In [62]:
Y_pred = grid.predict(X_test)

In [63]:
from sklearn.metrics import confusion_matrix, classification_report

In [64]:
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("\n")
print("Classification Report:\n",classification_report(Y_test, Y_pred))

Confusion Matrix:
 [[38  1]
 [ 3 72]]


Classification Report:
               precision    recall  f1-score   support

      Benign       0.93      0.97      0.95        39
   Malignant       0.99      0.96      0.97        75

    accuracy                           0.96       114
   macro avg       0.96      0.97      0.96       114
weighted avg       0.97      0.96      0.97       114



In [65]:
from sklearn import metrics
pos_label=['Benign', 'Malignant']
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("Precision:",metrics.precision_score(Y_test, Y_pred, pos_label= "Malignant"))
print("Recall:",metrics.recall_score(Y_test, Y_pred, pos_label= "Malignant"))

Accuracy: 0.9649122807017544
Precision: 0.9863013698630136
Recall: 0.96


In [66]:
# Run SVM with rbf kernel and C=100.0
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix

In [67]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit=True, cv=5)
grid.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']})

In [68]:
# instantiate classifier with rbf kernel and C=10
svc=SVC(C=10.0) 
svc.fit(X_train,Y_train)
# make predictions on test set
Y_pred=svc.predict(X_test)
# compute and print accuracy score
print('Model accuracy score with rbf kernel and C=10.0 : {}'. format(accuracy_score(Y_test, Y_pred)))

Model accuracy score with rbf kernel and C=10.0 : 0.9824561403508771


In [69]:
# SVM with linear kernel
# SVM with linear kernel and C=100.0
linear_svc=SVC(kernel='linear', C=100.0) 
linear_svc.fit(X_train,Y_train)
# make predictions on test set
Y_pred_test=linear_svc.predict(X_test)
# compute and print accuracy score
print('Model accuracy score with linear kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(Y_test, Y_pred_test)))

Model accuracy score with linear kernel and C=100.0 : 0.9123


In [70]:
#SVM with polynomial kernel and C=1000.0
poly_svc100=SVC(kernel='poly', C=1000.0) 
# fit classifier to training set
poly_svc100.fit(X_train, Y_train)
# make predictions on test set
Y_pred=poly_svc100.predict(X_test)
# compute and print accuracy score
print('Model accuracy score with polynomial kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(Y_test, Y_pred)))

Model accuracy score with polynomial kernel and C=1000.0 : 0.9211


In [72]:
# Run SVM with sigmoid kernel
# instantiate classifier with sigmoid kernel and C=100.0
sigmoid_svc100=SVC(kernel='sigmoid', C=100.0) 
# fit classifier to training set
sigmoid_svc100.fit(X_train,Y_train)
# make predictions on test set
Y_pred=sigmoid_svc100.predict(X_test)
# compute and print accuracy score
print('Model accuracy score with sigmoid kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(Y_test, Y_pred)))

Model accuracy score with sigmoid kernel and C=100.0 : 0.9386
